### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by ChrisTitos** [thephpleague/geotools#103]
Hi,

The last release of this library is more than a year old, though many commits have been made to it since then. That was why I was using dev-master as a dependency. This unfortunately meant that [the upgrade to geocoder 4.0](https://github.com/thephpleague/geotools/pull/100) broke my application. Does this library follow semver? Most League packages do that right? That would have prevented this.

If you could release more often it would be great :)

**Comment by Nyholm** [comment]
Hey. 

Yes, this library follows semver. We, as any open source project should, take BC very seriously. But Semver is for releases, dev-master does not have any restrictions on BC (or actually working). 
The next release will naturally be a new minor version (since we are not above 1.0.0). 

With that said, I understand your situation you are in. I've recently become a maintainer of this lib and I will make sure we release more often. I will put in some work on this library the next few months. 
What you should do is to update your composer.json to something like: 

```json
"league/geotools": "dev-master#7042c1241dac8cab1a2e237c7bab95ad7b637f06"
```

**Comment by morrislaptop** [comment]
Can we release? `composer outdated` is driving me nuts!

**Comment by Nyholm** [comment]
I'll try to have a look this weekend

**Comment by Nyholm** [comment]
Have a look at #115. Please try the new master and see if you can find any bugs before 0.8.0 is released

**Comment by Nyholm** [comment]
Any updates here? Please comment on #115.

**Comment by morrislaptop** [comment]
I was only using midpoint and geohash features, so I'm afraid I can't give any real world feedback.

**Comment by Nyholm** [comment]
Give what you can and it will be better than just me testing.

**Comment by ChrisTitos** [comment]
I'm looking at the update, but I see the caching was changed to PSR6 so I need more time to change that before I can test (I don't have anything for PSR16 yet). Maybe an idea to (also) support PSR-16? Seems a lot simpler for this use case.

**Comment by Nyholm** [comment]
There is an bridge that you may use to easily convert from psr6 to 16. https://github.com/php-cache/simple-cache-bridge

New version was just released. We will have to try to release more often from now on.

**Comment by ChrisTitos** [comment]
Everything is working on my end. Thanks for the release 👍
