### ISSUE TITLE
Precision and scale of Coordinates

### ISSUE THREAD

**Issue by JHGitty** [thephpleague/geotools#64]
I want to save the Coordinate in a database with Doctrine2 under Symfony.

That because I need to know the required scale and precision for the coordinate.
Which is the best scale and precision for longitude and latitude?

Currently I have this:
```php
    /**
     * @ORM\Column(type="decimal", precision=10, scale=6, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=6, nullable=true)
     */
    private $longitude;
```

Is this precision and scale ok?

Maybe this should be written on README.md for other users.

**Comment by toin0u** [comment]
Hi @JHGitty, I think you need to use a bigger `precision` and `scale` because you can have values like `-79.976666666667`. Of course it depends to the precision you want :)

This is too Doctrine2 & MySQL specific see here: http://doctrine-orm.readthedocs.org/en/latest/reference/annotations-reference.html#column

So I prefer to not add it here - hope you understand :)
